name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  dev:
    name: 'Terraform (dev)'
    runs-on: self-hosted
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@main
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'dev'
          tf_actions_comment: true
