name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - main
jobs:
  root:
    name: 'Terraform (root)'
    runs-on: self-hosted
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@main
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
