name: Deploy Infrastructure
on:
  push:
    branches:
      - main

jobs:
  tf_fmt:
    name: terraform infrastructure
    runs-on: self-runner
    steps:

    - name: Checkout Repo
    - uses: actions/checkout@v1
   

    - name: Terraform Validate
    - run: cd ./dev    
    - uses: hashicorp/terraform-github-actions/init@v0.4.0
     

    - name: Terraform Validate 
    - run: cd ./dev        
    - uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform Apply  
    - run: cd ./dev        
    - uses: hashicorp/terraform-github-actions/apply@v0.4.0
 
